# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e43dea8762d1f28e5a9ac4b75d9cf1c5dd89a9e995385f94e9b5ebeca1d56c89280d7088f3d5a7f2880423c00e147bc7cbbdcbdb78d90969dccb36048f23bfc

test:
  secret_key_base: 19bf609ec2ca01414e839b8caeddec88870c67b5d606a85891d8dde299d303fd52ea23ffbd2f883713f40d44092a6e8934b13668c3064af972c81413a1f3bbbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
